//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemFramework.AppMessage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SystemFramework.AppMessage.MessageResource", typeof(MessageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}ต้องน้อยกว่า{1}.
        /// </summary>
        public static string E0001 {
            get {
                return ResourceManager.GetString("E0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณากรอก{0}.
        /// </summary>
        public static string E0002 {
            get {
                return ResourceManager.GetString("E0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to มีรายการนี้ในฐานข้อมูลแล้ว กรุณากรอกข้อมูลใหม่อีกครั้ง.
        /// </summary>
        public static string E0003 {
            get {
                return ResourceManager.GetString("E0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่พบ{0}.
        /// </summary>
        public static string E0004 {
            get {
                return ResourceManager.GetString("E0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาเลือก{0}.
        /// </summary>
        public static string E0005 {
            get {
                return ResourceManager.GetString("E0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูลไม่ถูกต้อง.
        /// </summary>
        public static string E0006 {
            get {
                return ResourceManager.GetString("E0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to พนักงานคนนี้ ไม่มีสิทธิ์ได้รับ{0}.
        /// </summary>
        public static string E0007 {
            get {
                return ResourceManager.GetString("E0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string E0008 {
            get {
                return ResourceManager.GetString("E0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string E0009 {
            get {
                return ResourceManager.GetString("E0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string E0010 {
            get {
                return ResourceManager.GetString("E0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string E0011 {
            get {
                return ResourceManager.GetString("E0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถ{0} เนื่องจาก{1} กรุณา{2}.
        /// </summary>
        public static string E0012 {
            get {
                return ResourceManager.GetString("E0012", resourceCulture);
            }
        }
    }
}
